import psycopg2
from urllib.parse import urlparse

# Connection string
dsn = "postgresql://postgres:Revelation$2033Jesus@db.tijsephkovqailbrwuzt.supabase.co:5432/postgres"

commands = [
    # 1. Update site_content table to support advanced features
    """
    ALTER TABLE site_content 
    ADD COLUMN IF NOT EXISTS title TEXT,
    ADD COLUMN IF NOT EXISTS body_text TEXT,
    ADD COLUMN IF NOT EXISTS media_url TEXT,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
    """,
    # 2. Recreate user_submissions table to match current requirements
    "DROP TABLE IF EXISTS user_submissions CASCADE",
    """
    CREATE TABLE user_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        type TEXT NOT NULL, -- 'signup', 'donation', 'comment'
        name TEXT,
        email TEXT,
        phone TEXT,
        message TEXT,
        amount DECIMAL(10, 2), -- for donations
        metadata JSONB -- for any extra data
    )
    """,
    # 3. Migrate existing signups to user_submissions
    """
    INSERT INTO user_submissions (created_at, type, name, email, phone, message)
    SELECT created_at, 'signup', name, email, phone, message FROM signups
    ON CONFLICT DO NOTHING;
    """,
    # 4. Enable RLS and Policies for user_submissions
    """
    ALTER TABLE user_submissions ENABLE ROW LEVEL SECURITY
    """,
    """
    DO $$ 
    BEGIN
        IF NOT EXISTS (
            SELECT FROM pg_catalog.pg_policies 
            WHERE tablename = 'user_submissions' AND policyname = 'Enable insert for anon users'
        ) THEN
            CREATE POLICY "Enable insert for anon users" ON user_submissions FOR INSERT WITH CHECK (true);
        END IF;
        
        IF NOT EXISTS (
            SELECT FROM pg_catalog.pg_policies 
            WHERE tablename = 'user_submissions' AND policyname = 'Enable read for authenticated users'
        ) THEN
            CREATE POLICY "Enable read for authenticated users" ON user_submissions FOR SELECT USING (auth.role() = 'authenticated');
        END IF;
    END
    $$;
    """
]

conn = psycopg2.connect(dsn)
try:
    with conn.cursor() as cur:
        for command in commands:
            cur.execute(command)
    conn.commit()
    print("Database schema updated successfully.")
except Exception as e:
    print(f"An error occurred: {e}")
    conn.rollback()
finally:
    conn.close()
