import psycopg2
from urllib.parse import urlparse

# Connection string provided by user
dsn = "postgresql://postgres:Revelation$2033Jesus@db.tijsephkovqailbrwuzt.supabase.co:5432/postgres"

commands = [
    """
    CREATE TABLE IF NOT EXISTS signups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT,
        message TEXT
    )
    """,
    """
    ALTER TABLE signups ENABLE ROW LEVEL SECURITY
    """,
    """
    DO $$ 
    BEGIN
        IF NOT EXISTS (
            SELECT FROM pg_catalog.pg_policies 
            WHERE tablename = 'signups' AND policyname = 'Enable insert for anon users'
        ) THEN
            CREATE POLICY "Enable insert for anon users" ON signups FOR INSERT WITH CHECK (true);
        END IF;
    END
    $$;
    """,
     """
    DO $$ 
    BEGIN
        IF NOT EXISTS (
            SELECT FROM pg_catalog.pg_policies 
            WHERE tablename = 'signups' AND policyname = 'Enable read for anon users'
        ) THEN
             CREATE POLICY "Enable read for anon users" ON signups FOR SELECT USING (true);
        END IF;
    END
    $$;
    """
]

conn = psycopg2.connect(dsn)
try:
    with conn.cursor() as cur:
        for command in commands:
            cur.execute(command)
    conn.commit()
    print("Table created and policies applied successfully.")
except Exception as e:
    print(f"An error occurred: {e}")
    conn.rollback()
finally:
    conn.close()
